# Generated by Django 4.2.7 on 2025-12-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={},
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_approve_projects',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_create_projects',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_manage_events',
        ),
        migrations.RemoveField(
            model_name='role',
            name='category',
        ),
        migrations.RemoveField(
            model_name='role',
            name='description',
        ),
        migrations.RemoveField(
            model_name='role',
            name='level',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phase',
        ),
        migrations.AddField(
            model_name='role',
            name='can_add_clubs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='can_add_competitions',
            field=models.BooleanField(default=False),
        ),
    ]
