# Generated by Django 4.2.7 on 2025-12-09 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_role_options_remove_role_can_approve_projects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='can_add_clubs',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_add_competitions',
        ),
    ]
