# Generated by Django 4.2.7 on 2025-12-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_role_can_add_clubs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_manage_clubs',
            field=models.BooleanField(default=False),
        ),
    ]
