# Generated by Django 4.2.7 on 2025-12-09 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_role_can_manage_clubs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='can_manage_clubs',
            new_name='can_add_clubs',
        ),
    ]
