# Generated by Django 4.2.7 on 2025-12-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_can_manage_clubs_role_can_add_clubs'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_manage_competitions',
            field=models.BooleanField(default=False),
        ),
    ]
