# Generated by Django 4.2.7 on 2025-12-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_role_can_manage_competitions'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_normal_student',
            field=models.BooleanField(default=False),
        ),
    ]
