# Generated by Django 4.2.29 on 2026-04-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_manage_gatepass',
            field=models.BooleanField(default=False),
        ),
    ]
