# Generated by Django 4.2.29 on 2026-05-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_role_can_manage_gatepass'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='show_in_duty_roster',
            field=models.BooleanField(default=False, help_text='Users with this role will appear in the duty roster by default'),
        ),
        migrations.AddField(
            model_name='user',
            name='show_in_duty_roster',
            field=models.BooleanField(blank=True, default=None, help_text="Controls whether this person appears in the duty roster. Leave blank to inherit from their role's setting. Tick to force-show, untick to force-hide regardless of role.", null=True),
        ),
    ]
