# Generated by Django 4.2.29 on 2026-09-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_role_show_in_duty_roster_user_show_in_duty_roster'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_manage_feedback',
            field=models.BooleanField(default=False),
        ),
    ]
