# Generated by Django 4.2.7 on 2025-12-11 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('subject', models.CharField(max_length=200)),
                ('body_template', models.TextField()),
                ('available_variables', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_type', models.CharField(max_length=50)),
                ('sent_to_count', models.IntegerField(default=0)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_for_meetings', models.BooleanField(default=True)),
                ('email_for_announcements', models.BooleanField(default=True)),
                ('email_for_duties', models.BooleanField(default=True)),
                ('email_for_discipline', models.BooleanField(default=True)),
                ('email_for_projects', models.BooleanField(default=True)),
                ('in_app_for_meetings', models.BooleanField(default=True)),
                ('in_app_for_announcements', models.BooleanField(default=True)),
                ('in_app_for_duties', models.BooleanField(default=True)),
                ('in_app_for_discipline', models.BooleanField(default=True)),
                ('in_app_for_projects', models.BooleanField(default=True)),
                ('daily_digest', models.BooleanField(default=False)),
                ('weekly_digest', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('MEETING_TODAY', 'Meeting Today'), ('MEETING_MORNING', 'Meeting Morning Reminder'), ('MEETING_10MIN', 'Meeting 10 Minute Reminder'), ('MEETING_CANCELLED', 'Meeting Cancelled'), ('MEETING_RESCHEDULED', 'Meeting Rescheduled'), ('DUTY_TODAY', 'Duty Today'), ('DUTY_ASSIGNED', 'Duty Assigned'), ('DUTY_MORNING', 'Duty Morning Reminder'), ('ANNOUNCEMENT_NEW', 'New Announcement'), ('ANNOUNCEMENT_IMPORTANT', 'Important Announcement'), ('COMPETITION_NEW', 'New Competition'), ('COMPETITION_DEADLINE', 'Competition Deadline Approaching'), ('COMPETITION_STARTING', 'Competition Starting Soon'), ('DISCIPLINE_WARNING', 'Discipline Warning (3+ Offenses)'), ('DISCIPLINE_DAILY_REPORT', 'Daily Discipline Report'), ('DISCIPLINE_NEW_OFFENSE', 'New Offense Recorded'), ('GENERAL', 'General Notification')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_snoozed', models.BooleanField(default=False)),
                ('snoozed_until', models.DateTimeField(blank=True, null=True)),
                ('send_email', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['recipient', 'created_at'], name='notificatio_recipie_f39341_idx')],
            },
        ),
    ]
