# Generated by Django 4.2.7 on 2025-12-08 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(max_length=200)),
                ('meeting_link', models.URLField(blank=True)),
                ('agenda', models.TextField(blank=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('morning_reminder_sent', models.BooleanField(default=False)),
                ('ten_min_reminder_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendee_roles', models.ManyToManyField(blank=True, related_name='meetings', to='accounts.role')),
                ('attendees', models.ManyToManyField(related_name='meetings_attending', to=settings.AUTH_USER_MODEL)),
                ('organized_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings_organized', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='MinutesOfMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('document', models.FileField(blank=True, null=True, upload_to='meetings/mom/')),
                ('action_items', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('emailed_to_phase_heads', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('absent', models.ManyToManyField(blank=True, related_name='meetings_absent', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mom', to='meetings.meeting')),
                ('present', models.ManyToManyField(blank=True, related_name='meetings_present', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moms_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Minutes of Meetings',
            },
        ),
        migrations.CreateModel(
            name='MeetingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('EXCUSED', 'Excused')], default='ABSENT', max_length=20)),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_marked', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='meetings.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_attendance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['meeting', 'user'],
                'unique_together': {('meeting', 'user')},
            },
        ),
    ]
