# Generated by Django 4.2.7 on 2025-12-08 12:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['date']},
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='ten_min_reminder_sent',
        ),
        migrations.RemoveField(
            model_name='meetingattendance',
            name='arrival_time',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='meetings_attending', to=settings.AUTH_USER_MODEL),
        ),
    ]
