# Generated by Django 4.2.7 on 2025-12-09 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='club_logos/')),
                ('member_count', models.PositiveIntegerField(default=0)),
                ('established_year', models.PositiveIntegerField()),
                ('established_by', models.CharField(help_text='Comma-separated names of founders', max_length=500)),
                ('tutors', models.CharField(help_text='Comma-separated names of faculty tutors', max_length=500)),
                ('status', models.CharField(choices=[('active', 'Active'), ('under_review', 'Under Review'), ('inactive', 'Inactive')], default='under_review', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clubs_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
