# Generated by Django 4.2.29 on 2026-04-04 12:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gatepass', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='dno',
            field=models.CharField(default='', max_length=50, verbose_name='D.No / Room Number'),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='parent_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='requested_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
