# Generated by Django 4.2.29 on 2026-04-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatepass', '0002_gatepass_dno_gatepass_name_gatepass_parent_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='ct_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Class Teacher Email (Optional)'),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='student_class',
            field=models.CharField(default='', max_length=50, verbose_name='Class'),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='student_section',
            field=models.CharField(default='', max_length=50, verbose_name='Section'),
        ),
    ]
