# Generated by Django 4.2.7 on 2025-12-08 12:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('duty_roster', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='duty',
            options={'ordering': ['date'], 'verbose_name_plural': 'Duties'},
        ),
        migrations.AlterUniqueTogether(
            name='duty',
            unique_together={('assigned_to', 'date', 'duty_type_name')},
        ),
        migrations.AddField(
            model_name='duty',
            name='subsidiary_area',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.RemoveField(
            model_name='duty',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='duty',
            name='start_time',
        ),
    ]
