# Generated by Django 4.2.7 on 2025-12-10 14:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplineRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('class_section', models.CharField(help_text='Format: e.g., 10A, 11B, 12C', max_length=10)),
                ('dno', models.CharField(help_text='Format: Dxxxxxx (e.g., D123456)', max_length=7, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_dno', message='Dno must be in format Dxxxxxx (e.g., D123456)', regex='^D\\d{6}$')])),
                ('offense_count', models.PositiveIntegerField(default=1, help_text='Number of times offense occurred')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discipline_records_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Discipline Record',
                'verbose_name_plural': 'Discipline Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
