# Generated by Django 4.2.7 on 2025-12-10 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinerecord',
            name='dno',
            field=models.CharField(help_text='Format: D followed by 4-8 digits (e.g., D1234 to D12345678)', max_length=9, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_dno', message='Dno must be in format D followed by 4-8 digits (e.g., D1234 to D12345678)', regex='^D\\d{4,8}$')]),
        ),
    ]
