# Generated by Django 4.2.7 on 2025-12-10 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0002_alter_disciplinerecord_dno'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffenseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('UNIFORM', 'Uniform Violation'), ('LATE', 'Late Arrival / Submission'), ('BEHAVIOR', 'Misbehavior'), ('ACADEMIC', 'Academic Misconduct'), ('ABSENCE', 'Unauthorized Absence'), ('SUBSTANCES', 'Substances'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Detailed reason for this offense')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offense_logs', to='discipline.disciplinerecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
