# Generated by Django 4.2.29 on 2026-05-25 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0003_offenselog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offenselog',
            name='category',
            field=models.CharField(choices=[('UNIFORM', 'Uniform Violation'), ('LATE', 'Late Arrival / Submission'), ('BEHAVIOR', 'Misbehavior'), ('ACADEMIC', 'Academic Misconduct'), ('ABSENCE', 'Unauthorized Absence'), ('SUBSTANCES', 'Substances'), ('VPN', 'VPN Usage'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
