# Generated by Django 4.2.29 on 2026-10-08 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discipline', '0004_alter_offenselog_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('RECORD', 'Discipline Record'), ('OFFENSE', 'Offense Log')], default='OFFENSE', max_length=10)),
                ('dno', models.CharField(blank=True, max_length=9)),
                ('student_name', models.CharField(blank=True, max_length=200)),
                ('class_section', models.CharField(blank=True, max_length=10)),
                ('offense_count', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('UNIFORM', 'Uniform Violation'), ('LATE', 'Late Arrival / Submission'), ('BEHAVIOR', 'Misbehavior'), ('ACADEMIC', 'Academic Misconduct'), ('ABSENCE', 'Unauthorized Absence'), ('SUBSTANCES', 'Substances'), ('VPN', 'VPN Usage'), ('OTHER', 'Other')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('deleted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True, help_text='Optional context for this deletion')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-deleted_at'],
                'indexes': [models.Index(fields=['deleted_at'], name='discipline__deleted_24caac_idx'), models.Index(fields=['dno'], name='discipline__dno_abfa61_idx')],
            },
        ),
    ]
