# Generated by Django 4.2.7 on 2025-12-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='participants',
            field=models.TextField(blank=True, help_text='Comma-separated list of participants'),
        ),
        migrations.DeleteModel(
            name='CompetitionParticipant',
        ),
    ]
