# Generated by Django 4.2.7 on 2026-03-26 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_competition_participants_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('team_name', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='competitions.competition')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('competition', 'email')},
            },
        ),
    ]
