# Generated by Django 4.2.29 on 2026-05-17 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name if not logged in', max_length=200)),
                ('email', models.EmailField(blank=True, help_text='Email if not logged in', max_length=254)),
                ('type', models.CharField(choices=[('FEEDBACK', 'Feedback'), ('BUG', 'Bug Report'), ('FEATURE_REQUEST', 'Feature Request'), ('PERFORMANCE', 'Performance Issue'), ('OTHER', 'Other')], default='FEEDBACK', max_length=20)),
                ('category', models.CharField(blank=True, help_text='e.g., Announcements, Clubs, Competitions, etc.', max_length=100)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('screenshot', models.ImageField(blank=True, help_text='Screenshot or image related to the issue', null=True, upload_to='feedback/screenshots/')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin/staff')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_assigned', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Feedback',
                'ordering': ['-created_at'],
                'permissions': [('can_manage_feedback', 'Can manage feedback and issues')],
            },
        ),
    ]
